%import common.WORD
%import common.NEWLINE

start: ((concept | property | value) _NEWLINE)+
concept: concept_name _NEWLINE definition
value: concept_name _NEWLINE "Concept type: individual concept"
property: name (" " name)*
concept_name: name (" " name)*
definition: "General Concept: " concept_name
?name: WORD
      | name ". " name -> dot_name
      | name "-" name -> dashed_name
      | name "/" name -> slashed_name

_NEWLINE: NEWLINE
